# Generated by Django 5.1.1 on 2024-09-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('quantity', models.IntegerField(default=0)),
                ('quantity_sd', models.IntegerField(default=0)),
                ('in_decks', models.IntegerField(default=0)),
                ('in_decks_sd', models.IntegerField(default=0)),
                ('in_bulk', models.IntegerField(default=0)),
                ('card_code', models.CharField(max_length=10)),
                ('set', models.CharField(max_length=4)),
                ('language', models.CharField(default='EN', max_length=2)),
                ('set_number', models.IntegerField(default=0)),
                ('card_type', models.CharField(choices=[('monster', 'Monster'), ('other', 'Other'), ('spell', 'Spell'), ('token', 'Token'), ('trap', 'Trap')], max_length=7)),
                ('card_subtype', models.CharField(choices=[('effect', 'Effect'), ('fusion', 'Fusion'), ('link', 'Link'), ('none', 'None'), ('normal', 'Normal'), ('ritual', 'Ritual'), ('synchro', 'Synchro'), ('xyz', 'Xyz')], default='None', max_length=10)),
                ('is_pendulum', models.BooleanField(default=False)),
                ('property', models.CharField(choices=[('continuous', 'Continuous'), ('counter', 'Counter'), ('equip', 'Equip'), ('field', 'Field'), ('normal', 'Normal'), ('quick-play', 'Quick-Play'), ('ritual', 'Ritual')], max_length=10)),
                ('attribute', models.CharField(choices=[('dark', 'DARK'), ('divine', 'DIVINE'), ('earth', 'EARTH'), ('fire', 'FIRE'), ('light', 'LIGHT'), ('none', 'None'), ('water', 'WATER'), ('wind', 'WIND')], default='None', max_length=6)),
                ('types', models.CharField(max_length=255)),
                ('effect_type', models.CharField(choices=[('effect', 'Effect'), ('flip', 'FLIP'), ('gemini', 'Gemini'), ('none', 'None'), ('spirit', 'Spirit')], default='None', max_length=25)),
                ('level', models.IntegerField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12)], default=0)),
                ('attack', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('passcode', models.IntegerField(default=0)),
                ('effect', models.TextField()),
                ('pendulum_effect', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
