# Generated by Django 5.1.1 on 2024-09-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ygo_collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='property',
            new_name='card_property',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='set',
            new_name='card_set',
        ),
        migrations.RemoveField(
            model_name='card',
            name='types',
        ),
        migrations.AddField(
            model_name='card',
            name='card_frame',
            field=models.CharField(choices=[('normal', 'Normal'), ('effect', 'Effect'), ('ritual', 'Ritual'), ('fusion', 'Fusion'), ('synchro', 'Synchro'), ('xyz', 'XYZ'), ('link', 'Link'), ('normal_pendulum', 'Normal Pendulum'), ('effect_pendulum', 'Effect Pendulum'), ('ritual_pendulum', 'Ritual Pendulum'), ('fusion_pendulum', 'Fusion Pendulum'), ('synchro_pendulum', 'Synchro Pendulum'), ('xyz_pendulum', 'XYZ Pendulum'), ('spell', 'Spell'), ('trap', 'Trap'), ('token', 'Token'), ('skill', 'Skill')], default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='card',
            name='monster_type',
            field=models.CharField(choices=[('aqua', 'Aqua'), ('beast', 'Beast'), ('beast-warrior', 'Beast-Warrior'), ('creator-god', 'Creator-God'), ('cyberse', 'Cyberse'), ('dinosaur', 'Dinosaur'), ('divine-beast', 'Divine-Beast'), ('dragon', 'Dragon'), ('fairy', 'Fairy'), ('fiend', 'Fiend'), ('fish', 'Fish'), ('illusion', 'Illusion'), ('insect', 'Insect'), ('machine', 'Machine'), ('none', 'None'), ('plant', 'Plant'), ('psychic', 'Psychic'), ('pyro', 'Pyro'), ('reptile', 'Reptile'), ('rock', 'Rock'), ('sea-serpent', 'Sea Serpent'), ('spellcaster', 'Spellcaster'), ('thunder', 'Thunder'), ('warrior', 'Warrior'), ('winged-beast', 'Winged Beast'), ('wyrm', 'Wyrm'), ('zombie', 'Zombie')], default='None', max_length=13),
        ),
        migrations.AddField(
            model_name='card',
            name='set_rarity',
            field=models.CharField(choices=[('collectors-rare', 'Collectors Rare'), ('common', 'Common'), ('extra-secret-rare', 'Extra Secret Rare'), ('ghost-rare', 'Ghost Rare'), ('gold-rare', 'Gold Rare'), ('gold-secret-rare', 'Gold Secret Rare'), ('holographic-rare', 'Holographic Rare'), ('mozaic-rare', 'Mozaic Rare'), ('oversized', 'Oversized'), ('parallel-rare', 'Parallel Rare'), ('platinum-rare', 'Platinum Rare'), ('platinum-secret-rare', 'Platinum Secret Rare'), ('premium-gold-rare', 'Premium Gold Rare'), ('quarter-century-secret-rare', 'Quarter Century Secret Rare'), ('rare', 'Rare'), ('secret-parallel-rare', 'Secret Parallel Rare'), ('secret-rare', 'Secret Rare'), ('shatterfoil', 'Shatterfoil'), ('special', 'Special'), ('starfoil-rare', 'Starfoil Rare'), ('starlight-rare', 'Starlight Rare'), ('super-parallel-rare', 'Super Parallel Rare'), ('super-rare', 'Super Rare'), ('token', 'Token'), ('ultimate-rare', 'Ultimate Rare'), ('ultra-parallel-rare', 'Ultra Parallel Rare'), ('ultra-rare', 'Ultra Rare'), ('unknown', 'Unknown')], default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('monster', 'Monster'), ('other', 'Other'), ('skill', 'Skill'), ('spell', 'Spell'), ('token', 'Token'), ('trap', 'Trap')], max_length=7),
        ),
    ]
