# Generated by Django 5.1.1 on 2024-09-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ygo_collection', '0002_rename_property_card_card_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='in_draft',
            field=models.IntegerField(default=0),
        ),
    ]
