name: ygo-ocr
dependencies:
  - python=3.12.5
  - pip=24.2
  - pip:
    - -r requirements/requirements.txt
variables:
  FILE_NAME: "Book 5.xlsx"
  SHEET_NAME: "YGO"
  HEADER: True
  OUTPUT_FOLDER: "/Users/andrewgibbons/Projects/output/ygo-ocr/"
  LOGFILE_PATH: "/Users/andrewgibbons/Projects/logs/"
  LOG_LEVEL: 20